### ISSUE TITLE
Add thumbnail images to News page

### ISSUE THREAD

**Issue by jonhenshaw** [jonhenshaw/Cointracker#4]
The News page would look a bit better with thumbnail images next to the article titles. These images may or may not be given by the Crypto Panic API. If not, consider checking out the Coin Gecko API.

**Comment by VasekS** [comment]
Thx @jonhenshaw! I noticed when trying to start the app I receive an error message: **Error: EMFILE: too many open files, watch at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:203:21)**

Have you or other developers run into the same issue? Maybe similar to this one: [rror: EMFILE: too many open files, watch at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:203:21)]

**Comment by jonhenshaw** [comment]
Honestly no I haven't had this issue before. I can help you out on Monday but I'm busy this weekend unfortunately
